#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraditionalChinese
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChineseStudy")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUniHan(UniHan instance);
    partial void UpdateUniHan(UniHan instance);
    partial void DeleteUniHan(UniHan instance);
    partial void InsertFullFarEast(FullFarEast instance);
    partial void UpdateFullFarEast(FullFarEast instance);
    partial void DeleteFullFarEast(FullFarEast instance);
    partial void InsertCharBopoPinCrit(CharBopoPinCrit instance);
    partial void UpdateCharBopoPinCrit(CharBopoPinCrit instance);
    partial void DeleteCharBopoPinCrit(CharBopoPinCrit instance);
    partial void InsertCeDictFull(CeDictFull instance);
    partial void UpdateCeDictFull(CeDictFull instance);
    partial void DeleteCeDictFull(CeDictFull instance);
    partial void InsertCeDict(CeDict instance);
    partial void UpdateCeDict(CeDict instance);
    partial void DeleteCeDict(CeDict instance);
    partial void InsertPinMypin(PinMypin instance);
    partial void UpdatePinMypin(PinMypin instance);
    partial void DeletePinMypin(PinMypin instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TraditionalChinese.Properties.Settings.Default.ChineseStudyConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UniHan> UniHans
		{
			get
			{
				return this.GetTable<UniHan>();
			}
		}
		
		public System.Data.Linq.Table<FullFarEast> FullFarEasts
		{
			get
			{
				return this.GetTable<FullFarEast>();
			}
		}
		
		public System.Data.Linq.Table<CharBopoPinCrit> CharBopoPinCrits
		{
			get
			{
				return this.GetTable<CharBopoPinCrit>();
			}
		}
		
		public System.Data.Linq.Table<CeDictFull> CeDictFulls
		{
			get
			{
				return this.GetTable<CeDictFull>();
			}
		}
		
		public System.Data.Linq.Table<CeDict> CeDicts
		{
			get
			{
				return this.GetTable<CeDict>();
			}
		}
		
		public System.Data.Linq.Table<PinMypin> PinMypins
		{
			get
			{
				return this.GetTable<PinMypin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UniHan")]
	public partial class UniHan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ns1_description;
		
		private string _cp;
		
		private string _kCompatibilityVariant;
		
		private string _kRSUnicode;
		
		private string _kIRG_GSource;
		
		private string _kIRG_TSource;
		
		private string _kIRG_JSource;
		
		private string _kIRG_KSource;
		
		private string _kIRG_KPSource;
		
		private string _kIRG_VSource;
		
		private string _kIRG_HSource;
		
		private string _kIRG_USource;
		
		private string _kIRG_MSource;
		
		private string _kCantonese;
		
		private string _kDefinition;
		
		private string _kHanYu;
		
		private string _kMandarin;
		
		private string _kCangjie;
		
		private string _kSemanticVariant;
		
		private System.Nullable<double> _kIRGHanyuDaZidian;
		
		private System.Nullable<double> _kIRGKangXi;
		
		private System.Nullable<double> _kTotalStrokes;
		
		private string _kCihaiT;
		
		private string _kSBGY;
		
		private string _kHanyuPinyin;
		
		private string _kJIS0213;
		
		private string _kNelson;
		
		private string _kRSAdobe_Japan1_6;
		
		private string _nt;
		
		private System.Nullable<double> _nv;
		
		private string _kCowles;
		
		private string _kMatthews;
		
		private System.Nullable<double> _kOtherNumeric;
		
		private string _kPhonetic;
		
		private string _kKPS1;
		
		private string _kGSR;
		
		private string _kFenn;
		
		private string _kFennIndex;
		
		private string _kKarlgren;
		
		private string _kHKSCS;
		
		private string _kXHC1983;
		
		private string _kMeyerWempe;
		
		private string _kTraditionalVariant;
		
		private string _kVietnamese;
		
		private string _kSimplifiedVariant;
		
		private string _kSpecializedSemanticVariant;
		
		private string _kLau;
		
		private string _kRSKanWa;
		
		private string _kCheungBauer;
		
		private string _kCheungBauerIndex;
		
		private string _kIICore;
		
		private string _kTang;
		
		private string _kZVariant;
		
		private string _kRSKangXi;
		
		private string _kJapaneseKun;
		
		private string _kJapaneseOn;
		
		private string _kKangXi;
		
		private string _kKPS0;
		
		private string _kMorohashi;
		
		private string _kGB0;
		
		private string _kGB1;
		
		private string _kCNS1986;
		
		private string _kCNS1992;
		
		private string _kJis0;
		
		private string _kKSC0;
		
		private string _kHangul;
		
		private string _kBigFive;
		
		private string _kCCCII;
		
		private string _kDaeJaweon;
		
		private string _kEACC;
		
		private string _kFrequency;
		
		private string _kGradeLevel;
		
		private string _kHDZRadBreak;
		
		private string _kHKGlyph;
		
		private string _kHanyuPinlu;
		
		private string _kIRGDaeJaweon;
		
		private string _kIRGDaiKanwaZiten;
		
		private string _kKorean;
		
		private string _kMainlandTelegraph;
		
		private string _kPrimaryNumeric;
		
		private string _kTaiwanTelegraph;
		
		private string _kXerox;
		
		private string _kFourCornerCode;
		
		private string _kGB5;
		
		private string _kJis1;
		
		private string _kPseudoGB1;
		
		private string _kGB3;
		
		private string _kGB8;
		
		private string _kKSC1;
		
		private string _kIBMJapan;
		
		private string _kRSJapanese;
		
		private string _kAccountingNumeric;
		
		private string _kRSKorean;
		
		private string _kGB7;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onns1_descriptionChanging(string value);
    partial void Onns1_descriptionChanged();
    partial void OncpChanging(string value);
    partial void OncpChanged();
    partial void OnkCompatibilityVariantChanging(string value);
    partial void OnkCompatibilityVariantChanged();
    partial void OnkRSUnicodeChanging(string value);
    partial void OnkRSUnicodeChanged();
    partial void OnkIRG_GSourceChanging(string value);
    partial void OnkIRG_GSourceChanged();
    partial void OnkIRG_TSourceChanging(string value);
    partial void OnkIRG_TSourceChanged();
    partial void OnkIRG_JSourceChanging(string value);
    partial void OnkIRG_JSourceChanged();
    partial void OnkIRG_KSourceChanging(string value);
    partial void OnkIRG_KSourceChanged();
    partial void OnkIRG_KPSourceChanging(string value);
    partial void OnkIRG_KPSourceChanged();
    partial void OnkIRG_VSourceChanging(string value);
    partial void OnkIRG_VSourceChanged();
    partial void OnkIRG_HSourceChanging(string value);
    partial void OnkIRG_HSourceChanged();
    partial void OnkIRG_USourceChanging(string value);
    partial void OnkIRG_USourceChanged();
    partial void OnkIRG_MSourceChanging(string value);
    partial void OnkIRG_MSourceChanged();
    partial void OnkCantoneseChanging(string value);
    partial void OnkCantoneseChanged();
    partial void OnkDefinitionChanging(string value);
    partial void OnkDefinitionChanged();
    partial void OnkHanYuChanging(string value);
    partial void OnkHanYuChanged();
    partial void OnkMandarinChanging(string value);
    partial void OnkMandarinChanged();
    partial void OnkCangjieChanging(string value);
    partial void OnkCangjieChanged();
    partial void OnkSemanticVariantChanging(string value);
    partial void OnkSemanticVariantChanged();
    partial void OnkIRGHanyuDaZidianChanging(System.Nullable<double> value);
    partial void OnkIRGHanyuDaZidianChanged();
    partial void OnkIRGKangXiChanging(System.Nullable<double> value);
    partial void OnkIRGKangXiChanged();
    partial void OnkTotalStrokesChanging(System.Nullable<double> value);
    partial void OnkTotalStrokesChanged();
    partial void OnkCihaiTChanging(string value);
    partial void OnkCihaiTChanged();
    partial void OnkSBGYChanging(string value);
    partial void OnkSBGYChanged();
    partial void OnkHanyuPinyinChanging(string value);
    partial void OnkHanyuPinyinChanged();
    partial void OnkJIS0213Changing(string value);
    partial void OnkJIS0213Changed();
    partial void OnkNelsonChanging(string value);
    partial void OnkNelsonChanged();
    partial void OnkRSAdobe_Japan1_6Changing(string value);
    partial void OnkRSAdobe_Japan1_6Changed();
    partial void OnntChanging(string value);
    partial void OnntChanged();
    partial void OnnvChanging(System.Nullable<double> value);
    partial void OnnvChanged();
    partial void OnkCowlesChanging(string value);
    partial void OnkCowlesChanged();
    partial void OnkMatthewsChanging(string value);
    partial void OnkMatthewsChanged();
    partial void OnkOtherNumericChanging(System.Nullable<double> value);
    partial void OnkOtherNumericChanged();
    partial void OnkPhoneticChanging(string value);
    partial void OnkPhoneticChanged();
    partial void OnkKPS1Changing(string value);
    partial void OnkKPS1Changed();
    partial void OnkGSRChanging(string value);
    partial void OnkGSRChanged();
    partial void OnkFennChanging(string value);
    partial void OnkFennChanged();
    partial void OnkFennIndexChanging(string value);
    partial void OnkFennIndexChanged();
    partial void OnkKarlgrenChanging(string value);
    partial void OnkKarlgrenChanged();
    partial void OnkHKSCSChanging(string value);
    partial void OnkHKSCSChanged();
    partial void OnkXHC1983Changing(string value);
    partial void OnkXHC1983Changed();
    partial void OnkMeyerWempeChanging(string value);
    partial void OnkMeyerWempeChanged();
    partial void OnkTraditionalVariantChanging(string value);
    partial void OnkTraditionalVariantChanged();
    partial void OnkVietnameseChanging(string value);
    partial void OnkVietnameseChanged();
    partial void OnkSimplifiedVariantChanging(string value);
    partial void OnkSimplifiedVariantChanged();
    partial void OnkSpecializedSemanticVariantChanging(string value);
    partial void OnkSpecializedSemanticVariantChanged();
    partial void OnkLauChanging(string value);
    partial void OnkLauChanged();
    partial void OnkRSKanWaChanging(string value);
    partial void OnkRSKanWaChanged();
    partial void OnkCheungBauerChanging(string value);
    partial void OnkCheungBauerChanged();
    partial void OnkCheungBauerIndexChanging(string value);
    partial void OnkCheungBauerIndexChanged();
    partial void OnkIICoreChanging(string value);
    partial void OnkIICoreChanged();
    partial void OnkTangChanging(string value);
    partial void OnkTangChanged();
    partial void OnkZVariantChanging(string value);
    partial void OnkZVariantChanged();
    partial void OnkRSKangXiChanging(string value);
    partial void OnkRSKangXiChanged();
    partial void OnkJapaneseKunChanging(string value);
    partial void OnkJapaneseKunChanged();
    partial void OnkJapaneseOnChanging(string value);
    partial void OnkJapaneseOnChanged();
    partial void OnkKangXiChanging(string value);
    partial void OnkKangXiChanged();
    partial void OnkKPS0Changing(string value);
    partial void OnkKPS0Changed();
    partial void OnkMorohashiChanging(string value);
    partial void OnkMorohashiChanged();
    partial void OnkGB0Changing(string value);
    partial void OnkGB0Changed();
    partial void OnkGB1Changing(string value);
    partial void OnkGB1Changed();
    partial void OnkCNS1986Changing(string value);
    partial void OnkCNS1986Changed();
    partial void OnkCNS1992Changing(string value);
    partial void OnkCNS1992Changed();
    partial void OnkJis0Changing(string value);
    partial void OnkJis0Changed();
    partial void OnkKSC0Changing(string value);
    partial void OnkKSC0Changed();
    partial void OnkHangulChanging(string value);
    partial void OnkHangulChanged();
    partial void OnkBigFiveChanging(string value);
    partial void OnkBigFiveChanged();
    partial void OnkCCCIIChanging(string value);
    partial void OnkCCCIIChanged();
    partial void OnkDaeJaweonChanging(string value);
    partial void OnkDaeJaweonChanged();
    partial void OnkEACCChanging(string value);
    partial void OnkEACCChanged();
    partial void OnkFrequencyChanging(string value);
    partial void OnkFrequencyChanged();
    partial void OnkGradeLevelChanging(string value);
    partial void OnkGradeLevelChanged();
    partial void OnkHDZRadBreakChanging(string value);
    partial void OnkHDZRadBreakChanged();
    partial void OnkHKGlyphChanging(string value);
    partial void OnkHKGlyphChanged();
    partial void OnkHanyuPinluChanging(string value);
    partial void OnkHanyuPinluChanged();
    partial void OnkIRGDaeJaweonChanging(string value);
    partial void OnkIRGDaeJaweonChanged();
    partial void OnkIRGDaiKanwaZitenChanging(string value);
    partial void OnkIRGDaiKanwaZitenChanged();
    partial void OnkKoreanChanging(string value);
    partial void OnkKoreanChanged();
    partial void OnkMainlandTelegraphChanging(string value);
    partial void OnkMainlandTelegraphChanged();
    partial void OnkPrimaryNumericChanging(string value);
    partial void OnkPrimaryNumericChanged();
    partial void OnkTaiwanTelegraphChanging(string value);
    partial void OnkTaiwanTelegraphChanged();
    partial void OnkXeroxChanging(string value);
    partial void OnkXeroxChanged();
    partial void OnkFourCornerCodeChanging(string value);
    partial void OnkFourCornerCodeChanged();
    partial void OnkGB5Changing(string value);
    partial void OnkGB5Changed();
    partial void OnkJis1Changing(string value);
    partial void OnkJis1Changed();
    partial void OnkPseudoGB1Changing(string value);
    partial void OnkPseudoGB1Changed();
    partial void OnkGB3Changing(string value);
    partial void OnkGB3Changed();
    partial void OnkGB8Changing(string value);
    partial void OnkGB8Changed();
    partial void OnkKSC1Changing(string value);
    partial void OnkKSC1Changed();
    partial void OnkIBMJapanChanging(string value);
    partial void OnkIBMJapanChanged();
    partial void OnkRSJapaneseChanging(string value);
    partial void OnkRSJapaneseChanged();
    partial void OnkAccountingNumericChanging(string value);
    partial void OnkAccountingNumericChanged();
    partial void OnkRSKoreanChanging(string value);
    partial void OnkRSKoreanChanged();
    partial void OnkGB7Changing(string value);
    partial void OnkGB7Changed();
    partial void OnSSMA_TimeStampChanging(System.Data.Linq.Binary value);
    partial void OnSSMA_TimeStampChanged();
    #endregion
		
		public UniHan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ns1:description]", Storage="_ns1_description", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string ns1_description
		{
			get
			{
				return this._ns1_description;
			}
			set
			{
				if ((this._ns1_description != value))
				{
					this.Onns1_descriptionChanging(value);
					this.SendPropertyChanging();
					this._ns1_description = value;
					this.SendPropertyChanged("ns1_description");
					this.Onns1_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cp", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string cp
		{
			get
			{
				return this._cp;
			}
			set
			{
				if ((this._cp != value))
				{
					this.OncpChanging(value);
					this.SendPropertyChanging();
					this._cp = value;
					this.SendPropertyChanged("cp");
					this.OncpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCompatibilityVariant", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCompatibilityVariant
		{
			get
			{
				return this._kCompatibilityVariant;
			}
			set
			{
				if ((this._kCompatibilityVariant != value))
				{
					this.OnkCompatibilityVariantChanging(value);
					this.SendPropertyChanging();
					this._kCompatibilityVariant = value;
					this.SendPropertyChanged("kCompatibilityVariant");
					this.OnkCompatibilityVariantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kRSUnicode", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kRSUnicode
		{
			get
			{
				return this._kRSUnicode;
			}
			set
			{
				if ((this._kRSUnicode != value))
				{
					this.OnkRSUnicodeChanging(value);
					this.SendPropertyChanging();
					this._kRSUnicode = value;
					this.SendPropertyChanged("kRSUnicode");
					this.OnkRSUnicodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_GSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_GSource
		{
			get
			{
				return this._kIRG_GSource;
			}
			set
			{
				if ((this._kIRG_GSource != value))
				{
					this.OnkIRG_GSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_GSource = value;
					this.SendPropertyChanged("kIRG_GSource");
					this.OnkIRG_GSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_TSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_TSource
		{
			get
			{
				return this._kIRG_TSource;
			}
			set
			{
				if ((this._kIRG_TSource != value))
				{
					this.OnkIRG_TSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_TSource = value;
					this.SendPropertyChanged("kIRG_TSource");
					this.OnkIRG_TSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_JSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_JSource
		{
			get
			{
				return this._kIRG_JSource;
			}
			set
			{
				if ((this._kIRG_JSource != value))
				{
					this.OnkIRG_JSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_JSource = value;
					this.SendPropertyChanged("kIRG_JSource");
					this.OnkIRG_JSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_KSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_KSource
		{
			get
			{
				return this._kIRG_KSource;
			}
			set
			{
				if ((this._kIRG_KSource != value))
				{
					this.OnkIRG_KSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_KSource = value;
					this.SendPropertyChanged("kIRG_KSource");
					this.OnkIRG_KSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_KPSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_KPSource
		{
			get
			{
				return this._kIRG_KPSource;
			}
			set
			{
				if ((this._kIRG_KPSource != value))
				{
					this.OnkIRG_KPSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_KPSource = value;
					this.SendPropertyChanged("kIRG_KPSource");
					this.OnkIRG_KPSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_VSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_VSource
		{
			get
			{
				return this._kIRG_VSource;
			}
			set
			{
				if ((this._kIRG_VSource != value))
				{
					this.OnkIRG_VSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_VSource = value;
					this.SendPropertyChanged("kIRG_VSource");
					this.OnkIRG_VSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_HSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_HSource
		{
			get
			{
				return this._kIRG_HSource;
			}
			set
			{
				if ((this._kIRG_HSource != value))
				{
					this.OnkIRG_HSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_HSource = value;
					this.SendPropertyChanged("kIRG_HSource");
					this.OnkIRG_HSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_USource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_USource
		{
			get
			{
				return this._kIRG_USource;
			}
			set
			{
				if ((this._kIRG_USource != value))
				{
					this.OnkIRG_USourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_USource = value;
					this.SendPropertyChanged("kIRG_USource");
					this.OnkIRG_USourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRG_MSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRG_MSource
		{
			get
			{
				return this._kIRG_MSource;
			}
			set
			{
				if ((this._kIRG_MSource != value))
				{
					this.OnkIRG_MSourceChanging(value);
					this.SendPropertyChanging();
					this._kIRG_MSource = value;
					this.SendPropertyChanged("kIRG_MSource");
					this.OnkIRG_MSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCantonese", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCantonese
		{
			get
			{
				return this._kCantonese;
			}
			set
			{
				if ((this._kCantonese != value))
				{
					this.OnkCantoneseChanging(value);
					this.SendPropertyChanging();
					this._kCantonese = value;
					this.SendPropertyChanged("kCantonese");
					this.OnkCantoneseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kDefinition", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kDefinition
		{
			get
			{
				return this._kDefinition;
			}
			set
			{
				if ((this._kDefinition != value))
				{
					this.OnkDefinitionChanging(value);
					this.SendPropertyChanging();
					this._kDefinition = value;
					this.SendPropertyChanged("kDefinition");
					this.OnkDefinitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kHanYu", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kHanYu
		{
			get
			{
				return this._kHanYu;
			}
			set
			{
				if ((this._kHanYu != value))
				{
					this.OnkHanYuChanging(value);
					this.SendPropertyChanging();
					this._kHanYu = value;
					this.SendPropertyChanged("kHanYu");
					this.OnkHanYuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kMandarin", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kMandarin
		{
			get
			{
				return this._kMandarin;
			}
			set
			{
				if ((this._kMandarin != value))
				{
					this.OnkMandarinChanging(value);
					this.SendPropertyChanging();
					this._kMandarin = value;
					this.SendPropertyChanged("kMandarin");
					this.OnkMandarinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCangjie", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCangjie
		{
			get
			{
				return this._kCangjie;
			}
			set
			{
				if ((this._kCangjie != value))
				{
					this.OnkCangjieChanging(value);
					this.SendPropertyChanging();
					this._kCangjie = value;
					this.SendPropertyChanged("kCangjie");
					this.OnkCangjieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kSemanticVariant", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kSemanticVariant
		{
			get
			{
				return this._kSemanticVariant;
			}
			set
			{
				if ((this._kSemanticVariant != value))
				{
					this.OnkSemanticVariantChanging(value);
					this.SendPropertyChanging();
					this._kSemanticVariant = value;
					this.SendPropertyChanged("kSemanticVariant");
					this.OnkSemanticVariantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRGHanyuDaZidian", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> kIRGHanyuDaZidian
		{
			get
			{
				return this._kIRGHanyuDaZidian;
			}
			set
			{
				if ((this._kIRGHanyuDaZidian != value))
				{
					this.OnkIRGHanyuDaZidianChanging(value);
					this.SendPropertyChanging();
					this._kIRGHanyuDaZidian = value;
					this.SendPropertyChanged("kIRGHanyuDaZidian");
					this.OnkIRGHanyuDaZidianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRGKangXi", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> kIRGKangXi
		{
			get
			{
				return this._kIRGKangXi;
			}
			set
			{
				if ((this._kIRGKangXi != value))
				{
					this.OnkIRGKangXiChanging(value);
					this.SendPropertyChanging();
					this._kIRGKangXi = value;
					this.SendPropertyChanged("kIRGKangXi");
					this.OnkIRGKangXiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kTotalStrokes", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> kTotalStrokes
		{
			get
			{
				return this._kTotalStrokes;
			}
			set
			{
				if ((this._kTotalStrokes != value))
				{
					this.OnkTotalStrokesChanging(value);
					this.SendPropertyChanging();
					this._kTotalStrokes = value;
					this.SendPropertyChanged("kTotalStrokes");
					this.OnkTotalStrokesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCihaiT", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCihaiT
		{
			get
			{
				return this._kCihaiT;
			}
			set
			{
				if ((this._kCihaiT != value))
				{
					this.OnkCihaiTChanging(value);
					this.SendPropertyChanging();
					this._kCihaiT = value;
					this.SendPropertyChanged("kCihaiT");
					this.OnkCihaiTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kSBGY", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kSBGY
		{
			get
			{
				return this._kSBGY;
			}
			set
			{
				if ((this._kSBGY != value))
				{
					this.OnkSBGYChanging(value);
					this.SendPropertyChanging();
					this._kSBGY = value;
					this.SendPropertyChanged("kSBGY");
					this.OnkSBGYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kHanyuPinyin", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kHanyuPinyin
		{
			get
			{
				return this._kHanyuPinyin;
			}
			set
			{
				if ((this._kHanyuPinyin != value))
				{
					this.OnkHanyuPinyinChanging(value);
					this.SendPropertyChanging();
					this._kHanyuPinyin = value;
					this.SendPropertyChanged("kHanyuPinyin");
					this.OnkHanyuPinyinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kJIS0213", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kJIS0213
		{
			get
			{
				return this._kJIS0213;
			}
			set
			{
				if ((this._kJIS0213 != value))
				{
					this.OnkJIS0213Changing(value);
					this.SendPropertyChanging();
					this._kJIS0213 = value;
					this.SendPropertyChanged("kJIS0213");
					this.OnkJIS0213Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kNelson", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kNelson
		{
			get
			{
				return this._kNelson;
			}
			set
			{
				if ((this._kNelson != value))
				{
					this.OnkNelsonChanging(value);
					this.SendPropertyChanging();
					this._kNelson = value;
					this.SendPropertyChanged("kNelson");
					this.OnkNelsonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kRSAdobe_Japan1_6", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kRSAdobe_Japan1_6
		{
			get
			{
				return this._kRSAdobe_Japan1_6;
			}
			set
			{
				if ((this._kRSAdobe_Japan1_6 != value))
				{
					this.OnkRSAdobe_Japan1_6Changing(value);
					this.SendPropertyChanging();
					this._kRSAdobe_Japan1_6 = value;
					this.SendPropertyChanged("kRSAdobe_Japan1_6");
					this.OnkRSAdobe_Japan1_6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nt", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string nt
		{
			get
			{
				return this._nt;
			}
			set
			{
				if ((this._nt != value))
				{
					this.OnntChanging(value);
					this.SendPropertyChanging();
					this._nt = value;
					this.SendPropertyChanged("nt");
					this.OnntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nv", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> nv
		{
			get
			{
				return this._nv;
			}
			set
			{
				if ((this._nv != value))
				{
					this.OnnvChanging(value);
					this.SendPropertyChanging();
					this._nv = value;
					this.SendPropertyChanged("nv");
					this.OnnvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCowles", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCowles
		{
			get
			{
				return this._kCowles;
			}
			set
			{
				if ((this._kCowles != value))
				{
					this.OnkCowlesChanging(value);
					this.SendPropertyChanging();
					this._kCowles = value;
					this.SendPropertyChanged("kCowles");
					this.OnkCowlesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kMatthews", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kMatthews
		{
			get
			{
				return this._kMatthews;
			}
			set
			{
				if ((this._kMatthews != value))
				{
					this.OnkMatthewsChanging(value);
					this.SendPropertyChanging();
					this._kMatthews = value;
					this.SendPropertyChanged("kMatthews");
					this.OnkMatthewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kOtherNumeric", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> kOtherNumeric
		{
			get
			{
				return this._kOtherNumeric;
			}
			set
			{
				if ((this._kOtherNumeric != value))
				{
					this.OnkOtherNumericChanging(value);
					this.SendPropertyChanging();
					this._kOtherNumeric = value;
					this.SendPropertyChanged("kOtherNumeric");
					this.OnkOtherNumericChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kPhonetic", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kPhonetic
		{
			get
			{
				return this._kPhonetic;
			}
			set
			{
				if ((this._kPhonetic != value))
				{
					this.OnkPhoneticChanging(value);
					this.SendPropertyChanging();
					this._kPhonetic = value;
					this.SendPropertyChanged("kPhonetic");
					this.OnkPhoneticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kKPS1", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kKPS1
		{
			get
			{
				return this._kKPS1;
			}
			set
			{
				if ((this._kKPS1 != value))
				{
					this.OnkKPS1Changing(value);
					this.SendPropertyChanging();
					this._kKPS1 = value;
					this.SendPropertyChanged("kKPS1");
					this.OnkKPS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGSR", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGSR
		{
			get
			{
				return this._kGSR;
			}
			set
			{
				if ((this._kGSR != value))
				{
					this.OnkGSRChanging(value);
					this.SendPropertyChanging();
					this._kGSR = value;
					this.SendPropertyChanged("kGSR");
					this.OnkGSRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kFenn", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kFenn
		{
			get
			{
				return this._kFenn;
			}
			set
			{
				if ((this._kFenn != value))
				{
					this.OnkFennChanging(value);
					this.SendPropertyChanging();
					this._kFenn = value;
					this.SendPropertyChanged("kFenn");
					this.OnkFennChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kFennIndex", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kFennIndex
		{
			get
			{
				return this._kFennIndex;
			}
			set
			{
				if ((this._kFennIndex != value))
				{
					this.OnkFennIndexChanging(value);
					this.SendPropertyChanging();
					this._kFennIndex = value;
					this.SendPropertyChanged("kFennIndex");
					this.OnkFennIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kKarlgren", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kKarlgren
		{
			get
			{
				return this._kKarlgren;
			}
			set
			{
				if ((this._kKarlgren != value))
				{
					this.OnkKarlgrenChanging(value);
					this.SendPropertyChanging();
					this._kKarlgren = value;
					this.SendPropertyChanged("kKarlgren");
					this.OnkKarlgrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kHKSCS", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kHKSCS
		{
			get
			{
				return this._kHKSCS;
			}
			set
			{
				if ((this._kHKSCS != value))
				{
					this.OnkHKSCSChanging(value);
					this.SendPropertyChanging();
					this._kHKSCS = value;
					this.SendPropertyChanged("kHKSCS");
					this.OnkHKSCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kXHC1983", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kXHC1983
		{
			get
			{
				return this._kXHC1983;
			}
			set
			{
				if ((this._kXHC1983 != value))
				{
					this.OnkXHC1983Changing(value);
					this.SendPropertyChanging();
					this._kXHC1983 = value;
					this.SendPropertyChanged("kXHC1983");
					this.OnkXHC1983Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kMeyerWempe", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kMeyerWempe
		{
			get
			{
				return this._kMeyerWempe;
			}
			set
			{
				if ((this._kMeyerWempe != value))
				{
					this.OnkMeyerWempeChanging(value);
					this.SendPropertyChanging();
					this._kMeyerWempe = value;
					this.SendPropertyChanged("kMeyerWempe");
					this.OnkMeyerWempeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kTraditionalVariant", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kTraditionalVariant
		{
			get
			{
				return this._kTraditionalVariant;
			}
			set
			{
				if ((this._kTraditionalVariant != value))
				{
					this.OnkTraditionalVariantChanging(value);
					this.SendPropertyChanging();
					this._kTraditionalVariant = value;
					this.SendPropertyChanged("kTraditionalVariant");
					this.OnkTraditionalVariantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kVietnamese", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kVietnamese
		{
			get
			{
				return this._kVietnamese;
			}
			set
			{
				if ((this._kVietnamese != value))
				{
					this.OnkVietnameseChanging(value);
					this.SendPropertyChanging();
					this._kVietnamese = value;
					this.SendPropertyChanged("kVietnamese");
					this.OnkVietnameseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kSimplifiedVariant", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kSimplifiedVariant
		{
			get
			{
				return this._kSimplifiedVariant;
			}
			set
			{
				if ((this._kSimplifiedVariant != value))
				{
					this.OnkSimplifiedVariantChanging(value);
					this.SendPropertyChanging();
					this._kSimplifiedVariant = value;
					this.SendPropertyChanged("kSimplifiedVariant");
					this.OnkSimplifiedVariantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kSpecializedSemanticVariant", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kSpecializedSemanticVariant
		{
			get
			{
				return this._kSpecializedSemanticVariant;
			}
			set
			{
				if ((this._kSpecializedSemanticVariant != value))
				{
					this.OnkSpecializedSemanticVariantChanging(value);
					this.SendPropertyChanging();
					this._kSpecializedSemanticVariant = value;
					this.SendPropertyChanged("kSpecializedSemanticVariant");
					this.OnkSpecializedSemanticVariantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kLau", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kLau
		{
			get
			{
				return this._kLau;
			}
			set
			{
				if ((this._kLau != value))
				{
					this.OnkLauChanging(value);
					this.SendPropertyChanging();
					this._kLau = value;
					this.SendPropertyChanged("kLau");
					this.OnkLauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kRSKanWa", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kRSKanWa
		{
			get
			{
				return this._kRSKanWa;
			}
			set
			{
				if ((this._kRSKanWa != value))
				{
					this.OnkRSKanWaChanging(value);
					this.SendPropertyChanging();
					this._kRSKanWa = value;
					this.SendPropertyChanged("kRSKanWa");
					this.OnkRSKanWaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCheungBauer", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCheungBauer
		{
			get
			{
				return this._kCheungBauer;
			}
			set
			{
				if ((this._kCheungBauer != value))
				{
					this.OnkCheungBauerChanging(value);
					this.SendPropertyChanging();
					this._kCheungBauer = value;
					this.SendPropertyChanged("kCheungBauer");
					this.OnkCheungBauerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCheungBauerIndex", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCheungBauerIndex
		{
			get
			{
				return this._kCheungBauerIndex;
			}
			set
			{
				if ((this._kCheungBauerIndex != value))
				{
					this.OnkCheungBauerIndexChanging(value);
					this.SendPropertyChanging();
					this._kCheungBauerIndex = value;
					this.SendPropertyChanged("kCheungBauerIndex");
					this.OnkCheungBauerIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIICore", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIICore
		{
			get
			{
				return this._kIICore;
			}
			set
			{
				if ((this._kIICore != value))
				{
					this.OnkIICoreChanging(value);
					this.SendPropertyChanging();
					this._kIICore = value;
					this.SendPropertyChanged("kIICore");
					this.OnkIICoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kTang", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kTang
		{
			get
			{
				return this._kTang;
			}
			set
			{
				if ((this._kTang != value))
				{
					this.OnkTangChanging(value);
					this.SendPropertyChanging();
					this._kTang = value;
					this.SendPropertyChanged("kTang");
					this.OnkTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kZVariant", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kZVariant
		{
			get
			{
				return this._kZVariant;
			}
			set
			{
				if ((this._kZVariant != value))
				{
					this.OnkZVariantChanging(value);
					this.SendPropertyChanging();
					this._kZVariant = value;
					this.SendPropertyChanged("kZVariant");
					this.OnkZVariantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kRSKangXi", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kRSKangXi
		{
			get
			{
				return this._kRSKangXi;
			}
			set
			{
				if ((this._kRSKangXi != value))
				{
					this.OnkRSKangXiChanging(value);
					this.SendPropertyChanging();
					this._kRSKangXi = value;
					this.SendPropertyChanged("kRSKangXi");
					this.OnkRSKangXiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kJapaneseKun", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kJapaneseKun
		{
			get
			{
				return this._kJapaneseKun;
			}
			set
			{
				if ((this._kJapaneseKun != value))
				{
					this.OnkJapaneseKunChanging(value);
					this.SendPropertyChanging();
					this._kJapaneseKun = value;
					this.SendPropertyChanged("kJapaneseKun");
					this.OnkJapaneseKunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kJapaneseOn", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kJapaneseOn
		{
			get
			{
				return this._kJapaneseOn;
			}
			set
			{
				if ((this._kJapaneseOn != value))
				{
					this.OnkJapaneseOnChanging(value);
					this.SendPropertyChanging();
					this._kJapaneseOn = value;
					this.SendPropertyChanged("kJapaneseOn");
					this.OnkJapaneseOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kKangXi", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kKangXi
		{
			get
			{
				return this._kKangXi;
			}
			set
			{
				if ((this._kKangXi != value))
				{
					this.OnkKangXiChanging(value);
					this.SendPropertyChanging();
					this._kKangXi = value;
					this.SendPropertyChanged("kKangXi");
					this.OnkKangXiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kKPS0", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kKPS0
		{
			get
			{
				return this._kKPS0;
			}
			set
			{
				if ((this._kKPS0 != value))
				{
					this.OnkKPS0Changing(value);
					this.SendPropertyChanging();
					this._kKPS0 = value;
					this.SendPropertyChanged("kKPS0");
					this.OnkKPS0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kMorohashi", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kMorohashi
		{
			get
			{
				return this._kMorohashi;
			}
			set
			{
				if ((this._kMorohashi != value))
				{
					this.OnkMorohashiChanging(value);
					this.SendPropertyChanging();
					this._kMorohashi = value;
					this.SendPropertyChanged("kMorohashi");
					this.OnkMorohashiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGB0", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGB0
		{
			get
			{
				return this._kGB0;
			}
			set
			{
				if ((this._kGB0 != value))
				{
					this.OnkGB0Changing(value);
					this.SendPropertyChanging();
					this._kGB0 = value;
					this.SendPropertyChanged("kGB0");
					this.OnkGB0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGB1", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGB1
		{
			get
			{
				return this._kGB1;
			}
			set
			{
				if ((this._kGB1 != value))
				{
					this.OnkGB1Changing(value);
					this.SendPropertyChanging();
					this._kGB1 = value;
					this.SendPropertyChanged("kGB1");
					this.OnkGB1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCNS1986", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCNS1986
		{
			get
			{
				return this._kCNS1986;
			}
			set
			{
				if ((this._kCNS1986 != value))
				{
					this.OnkCNS1986Changing(value);
					this.SendPropertyChanging();
					this._kCNS1986 = value;
					this.SendPropertyChanged("kCNS1986");
					this.OnkCNS1986Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCNS1992", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCNS1992
		{
			get
			{
				return this._kCNS1992;
			}
			set
			{
				if ((this._kCNS1992 != value))
				{
					this.OnkCNS1992Changing(value);
					this.SendPropertyChanging();
					this._kCNS1992 = value;
					this.SendPropertyChanged("kCNS1992");
					this.OnkCNS1992Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kJis0", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kJis0
		{
			get
			{
				return this._kJis0;
			}
			set
			{
				if ((this._kJis0 != value))
				{
					this.OnkJis0Changing(value);
					this.SendPropertyChanging();
					this._kJis0 = value;
					this.SendPropertyChanged("kJis0");
					this.OnkJis0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kKSC0", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kKSC0
		{
			get
			{
				return this._kKSC0;
			}
			set
			{
				if ((this._kKSC0 != value))
				{
					this.OnkKSC0Changing(value);
					this.SendPropertyChanging();
					this._kKSC0 = value;
					this.SendPropertyChanged("kKSC0");
					this.OnkKSC0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kHangul", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kHangul
		{
			get
			{
				return this._kHangul;
			}
			set
			{
				if ((this._kHangul != value))
				{
					this.OnkHangulChanging(value);
					this.SendPropertyChanging();
					this._kHangul = value;
					this.SendPropertyChanged("kHangul");
					this.OnkHangulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kBigFive", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kBigFive
		{
			get
			{
				return this._kBigFive;
			}
			set
			{
				if ((this._kBigFive != value))
				{
					this.OnkBigFiveChanging(value);
					this.SendPropertyChanging();
					this._kBigFive = value;
					this.SendPropertyChanged("kBigFive");
					this.OnkBigFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kCCCII", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kCCCII
		{
			get
			{
				return this._kCCCII;
			}
			set
			{
				if ((this._kCCCII != value))
				{
					this.OnkCCCIIChanging(value);
					this.SendPropertyChanging();
					this._kCCCII = value;
					this.SendPropertyChanged("kCCCII");
					this.OnkCCCIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kDaeJaweon", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kDaeJaweon
		{
			get
			{
				return this._kDaeJaweon;
			}
			set
			{
				if ((this._kDaeJaweon != value))
				{
					this.OnkDaeJaweonChanging(value);
					this.SendPropertyChanging();
					this._kDaeJaweon = value;
					this.SendPropertyChanged("kDaeJaweon");
					this.OnkDaeJaweonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kEACC", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kEACC
		{
			get
			{
				return this._kEACC;
			}
			set
			{
				if ((this._kEACC != value))
				{
					this.OnkEACCChanging(value);
					this.SendPropertyChanging();
					this._kEACC = value;
					this.SendPropertyChanged("kEACC");
					this.OnkEACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kFrequency", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kFrequency
		{
			get
			{
				return this._kFrequency;
			}
			set
			{
				if ((this._kFrequency != value))
				{
					this.OnkFrequencyChanging(value);
					this.SendPropertyChanging();
					this._kFrequency = value;
					this.SendPropertyChanged("kFrequency");
					this.OnkFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGradeLevel", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGradeLevel
		{
			get
			{
				return this._kGradeLevel;
			}
			set
			{
				if ((this._kGradeLevel != value))
				{
					this.OnkGradeLevelChanging(value);
					this.SendPropertyChanging();
					this._kGradeLevel = value;
					this.SendPropertyChanged("kGradeLevel");
					this.OnkGradeLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kHDZRadBreak", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kHDZRadBreak
		{
			get
			{
				return this._kHDZRadBreak;
			}
			set
			{
				if ((this._kHDZRadBreak != value))
				{
					this.OnkHDZRadBreakChanging(value);
					this.SendPropertyChanging();
					this._kHDZRadBreak = value;
					this.SendPropertyChanged("kHDZRadBreak");
					this.OnkHDZRadBreakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kHKGlyph", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kHKGlyph
		{
			get
			{
				return this._kHKGlyph;
			}
			set
			{
				if ((this._kHKGlyph != value))
				{
					this.OnkHKGlyphChanging(value);
					this.SendPropertyChanging();
					this._kHKGlyph = value;
					this.SendPropertyChanged("kHKGlyph");
					this.OnkHKGlyphChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kHanyuPinlu", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kHanyuPinlu
		{
			get
			{
				return this._kHanyuPinlu;
			}
			set
			{
				if ((this._kHanyuPinlu != value))
				{
					this.OnkHanyuPinluChanging(value);
					this.SendPropertyChanging();
					this._kHanyuPinlu = value;
					this.SendPropertyChanged("kHanyuPinlu");
					this.OnkHanyuPinluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRGDaeJaweon", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRGDaeJaweon
		{
			get
			{
				return this._kIRGDaeJaweon;
			}
			set
			{
				if ((this._kIRGDaeJaweon != value))
				{
					this.OnkIRGDaeJaweonChanging(value);
					this.SendPropertyChanging();
					this._kIRGDaeJaweon = value;
					this.SendPropertyChanged("kIRGDaeJaweon");
					this.OnkIRGDaeJaweonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIRGDaiKanwaZiten", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIRGDaiKanwaZiten
		{
			get
			{
				return this._kIRGDaiKanwaZiten;
			}
			set
			{
				if ((this._kIRGDaiKanwaZiten != value))
				{
					this.OnkIRGDaiKanwaZitenChanging(value);
					this.SendPropertyChanging();
					this._kIRGDaiKanwaZiten = value;
					this.SendPropertyChanged("kIRGDaiKanwaZiten");
					this.OnkIRGDaiKanwaZitenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kKorean", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kKorean
		{
			get
			{
				return this._kKorean;
			}
			set
			{
				if ((this._kKorean != value))
				{
					this.OnkKoreanChanging(value);
					this.SendPropertyChanging();
					this._kKorean = value;
					this.SendPropertyChanged("kKorean");
					this.OnkKoreanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kMainlandTelegraph", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kMainlandTelegraph
		{
			get
			{
				return this._kMainlandTelegraph;
			}
			set
			{
				if ((this._kMainlandTelegraph != value))
				{
					this.OnkMainlandTelegraphChanging(value);
					this.SendPropertyChanging();
					this._kMainlandTelegraph = value;
					this.SendPropertyChanged("kMainlandTelegraph");
					this.OnkMainlandTelegraphChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kPrimaryNumeric", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kPrimaryNumeric
		{
			get
			{
				return this._kPrimaryNumeric;
			}
			set
			{
				if ((this._kPrimaryNumeric != value))
				{
					this.OnkPrimaryNumericChanging(value);
					this.SendPropertyChanging();
					this._kPrimaryNumeric = value;
					this.SendPropertyChanged("kPrimaryNumeric");
					this.OnkPrimaryNumericChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kTaiwanTelegraph", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kTaiwanTelegraph
		{
			get
			{
				return this._kTaiwanTelegraph;
			}
			set
			{
				if ((this._kTaiwanTelegraph != value))
				{
					this.OnkTaiwanTelegraphChanging(value);
					this.SendPropertyChanging();
					this._kTaiwanTelegraph = value;
					this.SendPropertyChanged("kTaiwanTelegraph");
					this.OnkTaiwanTelegraphChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kXerox", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kXerox
		{
			get
			{
				return this._kXerox;
			}
			set
			{
				if ((this._kXerox != value))
				{
					this.OnkXeroxChanging(value);
					this.SendPropertyChanging();
					this._kXerox = value;
					this.SendPropertyChanged("kXerox");
					this.OnkXeroxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kFourCornerCode", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kFourCornerCode
		{
			get
			{
				return this._kFourCornerCode;
			}
			set
			{
				if ((this._kFourCornerCode != value))
				{
					this.OnkFourCornerCodeChanging(value);
					this.SendPropertyChanging();
					this._kFourCornerCode = value;
					this.SendPropertyChanged("kFourCornerCode");
					this.OnkFourCornerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGB5", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGB5
		{
			get
			{
				return this._kGB5;
			}
			set
			{
				if ((this._kGB5 != value))
				{
					this.OnkGB5Changing(value);
					this.SendPropertyChanging();
					this._kGB5 = value;
					this.SendPropertyChanged("kGB5");
					this.OnkGB5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kJis1", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kJis1
		{
			get
			{
				return this._kJis1;
			}
			set
			{
				if ((this._kJis1 != value))
				{
					this.OnkJis1Changing(value);
					this.SendPropertyChanging();
					this._kJis1 = value;
					this.SendPropertyChanged("kJis1");
					this.OnkJis1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kPseudoGB1", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kPseudoGB1
		{
			get
			{
				return this._kPseudoGB1;
			}
			set
			{
				if ((this._kPseudoGB1 != value))
				{
					this.OnkPseudoGB1Changing(value);
					this.SendPropertyChanging();
					this._kPseudoGB1 = value;
					this.SendPropertyChanged("kPseudoGB1");
					this.OnkPseudoGB1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGB3", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGB3
		{
			get
			{
				return this._kGB3;
			}
			set
			{
				if ((this._kGB3 != value))
				{
					this.OnkGB3Changing(value);
					this.SendPropertyChanging();
					this._kGB3 = value;
					this.SendPropertyChanged("kGB3");
					this.OnkGB3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGB8", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGB8
		{
			get
			{
				return this._kGB8;
			}
			set
			{
				if ((this._kGB8 != value))
				{
					this.OnkGB8Changing(value);
					this.SendPropertyChanging();
					this._kGB8 = value;
					this.SendPropertyChanged("kGB8");
					this.OnkGB8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kKSC1", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kKSC1
		{
			get
			{
				return this._kKSC1;
			}
			set
			{
				if ((this._kKSC1 != value))
				{
					this.OnkKSC1Changing(value);
					this.SendPropertyChanging();
					this._kKSC1 = value;
					this.SendPropertyChanged("kKSC1");
					this.OnkKSC1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kIBMJapan", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kIBMJapan
		{
			get
			{
				return this._kIBMJapan;
			}
			set
			{
				if ((this._kIBMJapan != value))
				{
					this.OnkIBMJapanChanging(value);
					this.SendPropertyChanging();
					this._kIBMJapan = value;
					this.SendPropertyChanged("kIBMJapan");
					this.OnkIBMJapanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kRSJapanese", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kRSJapanese
		{
			get
			{
				return this._kRSJapanese;
			}
			set
			{
				if ((this._kRSJapanese != value))
				{
					this.OnkRSJapaneseChanging(value);
					this.SendPropertyChanging();
					this._kRSJapanese = value;
					this.SendPropertyChanged("kRSJapanese");
					this.OnkRSJapaneseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kAccountingNumeric", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kAccountingNumeric
		{
			get
			{
				return this._kAccountingNumeric;
			}
			set
			{
				if ((this._kAccountingNumeric != value))
				{
					this.OnkAccountingNumericChanging(value);
					this.SendPropertyChanging();
					this._kAccountingNumeric = value;
					this.SendPropertyChanged("kAccountingNumeric");
					this.OnkAccountingNumericChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kRSKorean", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kRSKorean
		{
			get
			{
				return this._kRSKorean;
			}
			set
			{
				if ((this._kRSKorean != value))
				{
					this.OnkRSKoreanChanging(value);
					this.SendPropertyChanging();
					this._kRSKorean = value;
					this.SendPropertyChanged("kRSKorean");
					this.OnkRSKoreanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kGB7", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string kGB7
		{
			get
			{
				return this._kGB7;
			}
			set
			{
				if ((this._kGB7 != value))
				{
					this.OnkGB7Changing(value);
					this.SendPropertyChanging();
					this._kGB7 = value;
					this.SendPropertyChanged("kGB7");
					this.OnkGB7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this.OnSSMA_TimeStampChanging(value);
					this.SendPropertyChanging();
					this._SSMA_TimeStamp = value;
					this.SendPropertyChanged("SSMA_TimeStamp");
					this.OnSSMA_TimeStampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FullFarEast")]
	public partial class FullFarEast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Bopo;
		
		private string _Char;
		
		private string _FeNumber;
		
		private string _English;
		
		private string _Hex;
		
		private string _Cji;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBopoChanging(string value);
    partial void OnBopoChanged();
    partial void OnCharChanging(string value);
    partial void OnCharChanged();
    partial void OnFeNumberChanging(string value);
    partial void OnFeNumberChanged();
    partial void OnEnglishChanging(string value);
    partial void OnEnglishChanged();
    partial void OnHexChanging(string value);
    partial void OnHexChanged();
    partial void OnCjiChanging(string value);
    partial void OnCjiChanged();
    #endregion
		
		public FullFarEast()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bopo", DbType="NVarChar(255)")]
		public string Bopo
		{
			get
			{
				return this._Bopo;
			}
			set
			{
				if ((this._Bopo != value))
				{
					this.OnBopoChanging(value);
					this.SendPropertyChanging();
					this._Bopo = value;
					this.SendPropertyChanged("Bopo");
					this.OnBopoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Char", DbType="NVarChar(255)")]
		public string Char
		{
			get
			{
				return this._Char;
			}
			set
			{
				if ((this._Char != value))
				{
					this.OnCharChanging(value);
					this.SendPropertyChanging();
					this._Char = value;
					this.SendPropertyChanged("Char");
					this.OnCharChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeNumber", DbType="NVarChar(255)")]
		public string FeNumber
		{
			get
			{
				return this._FeNumber;
			}
			set
			{
				if ((this._FeNumber != value))
				{
					this.OnFeNumberChanging(value);
					this.SendPropertyChanging();
					this._FeNumber = value;
					this.SendPropertyChanged("FeNumber");
					this.OnFeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English", DbType="NVarChar(255)")]
		public string English
		{
			get
			{
				return this._English;
			}
			set
			{
				if ((this._English != value))
				{
					this.OnEnglishChanging(value);
					this.SendPropertyChanging();
					this._English = value;
					this.SendPropertyChanged("English");
					this.OnEnglishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hex", DbType="NVarChar(255)")]
		public string Hex
		{
			get
			{
				return this._Hex;
			}
			set
			{
				if ((this._Hex != value))
				{
					this.OnHexChanging(value);
					this.SendPropertyChanging();
					this._Hex = value;
					this.SendPropertyChanged("Hex");
					this.OnHexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cji", DbType="NVarChar(255)")]
		public string Cji
		{
			get
			{
				return this._Cji;
			}
			set
			{
				if ((this._Cji != value))
				{
					this.OnCjiChanging(value);
					this.SendPropertyChanging();
					this._Cji = value;
					this.SendPropertyChanged("Cji");
					this.OnCjiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CharBopoPinCrit")]
	public partial class CharBopoPinCrit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Char;
		
		private string _Bopo;
		
		private string _Pin;
		
		private string _Crit;
		
		private string _Cji;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCharChanging(string value);
    partial void OnCharChanged();
    partial void OnBopoChanging(string value);
    partial void OnBopoChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnCritChanging(string value);
    partial void OnCritChanged();
    partial void OnCjiChanging(string value);
    partial void OnCjiChanged();
    #endregion
		
		public CharBopoPinCrit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Char", DbType="NVarChar(255)")]
		public string Char
		{
			get
			{
				return this._Char;
			}
			set
			{
				if ((this._Char != value))
				{
					this.OnCharChanging(value);
					this.SendPropertyChanging();
					this._Char = value;
					this.SendPropertyChanged("Char");
					this.OnCharChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bopo", DbType="NVarChar(255)")]
		public string Bopo
		{
			get
			{
				return this._Bopo;
			}
			set
			{
				if ((this._Bopo != value))
				{
					this.OnBopoChanging(value);
					this.SendPropertyChanging();
					this._Bopo = value;
					this.SendPropertyChanged("Bopo");
					this.OnBopoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="NVarChar(255)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Crit", DbType="NVarChar(255)")]
		public string Crit
		{
			get
			{
				return this._Crit;
			}
			set
			{
				if ((this._Crit != value))
				{
					this.OnCritChanging(value);
					this.SendPropertyChanging();
					this._Crit = value;
					this.SendPropertyChanged("Crit");
					this.OnCritChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cji", DbType="NVarChar(255)")]
		public string Cji
		{
			get
			{
				return this._Cji;
			}
			set
			{
				if ((this._Cji != value))
				{
					this.OnCjiChanging(value);
					this.SendPropertyChanging();
					this._Cji = value;
					this.SendPropertyChanged("Cji");
					this.OnCjiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CeDictFull")]
	public partial class CeDictFull : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BoPoMoFo;
		
		private string _Traditional;
		
		private string _Simplified;
		
		private string _Pinyin;
		
		private string _English;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBoPoMoFoChanging(string value);
    partial void OnBoPoMoFoChanged();
    partial void OnTraditionalChanging(string value);
    partial void OnTraditionalChanged();
    partial void OnSimplifiedChanging(string value);
    partial void OnSimplifiedChanged();
    partial void OnPinyinChanging(string value);
    partial void OnPinyinChanged();
    partial void OnEnglishChanging(string value);
    partial void OnEnglishChanged();
    #endregion
		
		public CeDictFull()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoPoMoFo", DbType="NVarChar(255)")]
		public string BoPoMoFo
		{
			get
			{
				return this._BoPoMoFo;
			}
			set
			{
				if ((this._BoPoMoFo != value))
				{
					this.OnBoPoMoFoChanging(value);
					this.SendPropertyChanging();
					this._BoPoMoFo = value;
					this.SendPropertyChanged("BoPoMoFo");
					this.OnBoPoMoFoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Traditional", DbType="NVarChar(255)")]
		public string Traditional
		{
			get
			{
				return this._Traditional;
			}
			set
			{
				if ((this._Traditional != value))
				{
					this.OnTraditionalChanging(value);
					this.SendPropertyChanging();
					this._Traditional = value;
					this.SendPropertyChanged("Traditional");
					this.OnTraditionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Simplified", DbType="NVarChar(255)")]
		public string Simplified
		{
			get
			{
				return this._Simplified;
			}
			set
			{
				if ((this._Simplified != value))
				{
					this.OnSimplifiedChanging(value);
					this.SendPropertyChanging();
					this._Simplified = value;
					this.SendPropertyChanged("Simplified");
					this.OnSimplifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pinyin", DbType="NVarChar(255)")]
		public string Pinyin
		{
			get
			{
				return this._Pinyin;
			}
			set
			{
				if ((this._Pinyin != value))
				{
					this.OnPinyinChanging(value);
					this.SendPropertyChanging();
					this._Pinyin = value;
					this.SendPropertyChanged("Pinyin");
					this.OnPinyinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English", DbType="NVarChar(255)")]
		public string English
		{
			get
			{
				return this._English;
			}
			set
			{
				if ((this._English != value))
				{
					this.OnEnglishChanging(value);
					this.SendPropertyChanging();
					this._English = value;
					this.SendPropertyChanged("English");
					this.OnEnglishChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CeDict")]
	public partial class CeDict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Bopo;
		
		private string _Char;
		
		private string _English;
		
		private string _Pinyin;
		
		private string _Hex;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBopoChanging(string value);
    partial void OnBopoChanged();
    partial void OnCharChanging(string value);
    partial void OnCharChanged();
    partial void OnEnglishChanging(string value);
    partial void OnEnglishChanged();
    partial void OnPinyinChanging(string value);
    partial void OnPinyinChanged();
    partial void OnHexChanging(string value);
    partial void OnHexChanged();
    #endregion
		
		public CeDict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bopo", DbType="NVarChar(255)")]
		public string Bopo
		{
			get
			{
				return this._Bopo;
			}
			set
			{
				if ((this._Bopo != value))
				{
					this.OnBopoChanging(value);
					this.SendPropertyChanging();
					this._Bopo = value;
					this.SendPropertyChanged("Bopo");
					this.OnBopoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Char", DbType="NVarChar(255)")]
		public string Char
		{
			get
			{
				return this._Char;
			}
			set
			{
				if ((this._Char != value))
				{
					this.OnCharChanging(value);
					this.SendPropertyChanging();
					this._Char = value;
					this.SendPropertyChanged("Char");
					this.OnCharChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English", DbType="NVarChar(255)")]
		public string English
		{
			get
			{
				return this._English;
			}
			set
			{
				if ((this._English != value))
				{
					this.OnEnglishChanging(value);
					this.SendPropertyChanging();
					this._English = value;
					this.SendPropertyChanged("English");
					this.OnEnglishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pinyin", DbType="NVarChar(255)")]
		public string Pinyin
		{
			get
			{
				return this._Pinyin;
			}
			set
			{
				if ((this._Pinyin != value))
				{
					this.OnPinyinChanging(value);
					this.SendPropertyChanging();
					this._Pinyin = value;
					this.SendPropertyChanged("Pinyin");
					this.OnPinyinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hex", DbType="NVarChar(255)")]
		public string Hex
		{
			get
			{
				return this._Hex;
			}
			set
			{
				if ((this._Hex != value))
				{
					this.OnHexChanging(value);
					this.SendPropertyChanging();
					this._Hex = value;
					this.SendPropertyChanged("Hex");
					this.OnHexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PinMypin")]
	public partial class PinMypin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Pin;
		
		private string _Mypin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnMypinChanging(string value);
    partial void OnMypinChanged();
    #endregion
		
		public PinMypin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="NVarChar(255)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mypin", DbType="NVarChar(255)")]
		public string Mypin
		{
			get
			{
				return this._Mypin;
			}
			set
			{
				if ((this._Mypin != value))
				{
					this.OnMypinChanging(value);
					this.SendPropertyChanging();
					this._Mypin = value;
					this.SendPropertyChanged("Mypin");
					this.OnMypinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
