//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraditionalChinese.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb1essy2yr.database.windows.net;Initial Catalog=ChineseStudy;Persist " +
            "Security Info=True;User ID=GalleryServerPro;Password=GalleryOnAzure3870!")]
        public string ChineseStudyConnectionString1 {
            get {
                return ((string)(this["ChineseStudyConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb1essy2yr.database.windows.net;Initial Catalog=ChineseStudy;Persist " +
            "Security Info=True;User ID=GalleryServerPro;Password=GalleryOnAzure3870!")]
        public string ChineseStudyConnectionString {
            get {
                return ((string)(this["ChineseStudyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb1essy2yr.database.windows.net;Initial Catalog=ChineseStudy;Persist " +
            "Security Info=True;User ID=GalleryServerPro;Password=GalleryOnAzure3870!")]
        public string ChineseStudyConnectionString2 {
            get {
                return ((string)(this["ChineseStudyConnectionString2"]));
            }
        }
    }
}
